- name: Deploy Flask App
  hosts: app
  become: yes

  vars:
    app_dir: /opt/flaskapp

  tasks:
    - name: Instalar Python3 y pip
      apt:
        name:
          - python3
          - python3-pip
        update_cache: yes
        state: present

    - name: Crear carpeta de aplicación
      file:
        path: "{{ app_dir }}"
        state: directory

    - name: Copiar aplicación
      copy:
        src: ../app/
        dest: "{{ app_dir }}"
    
    - name: Instalar dependencias
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        executable: pip3

    - name: Ejecutar aplicación Flask
      shell: |
        nohup python3 {{ app_dir }}/main.py &